### ISSUE TITLE
AttributeError when running code

### ISSUE THREAD

**Issue by ghost** [mirceamironenco/BayesianRecurrentNN#3]
Hi, I am trying to run this code with **tensorflow 1.3.0** and **Python3.6**

I get a similar error to a separate issue raised:

```
Traceback (most recent call last):
  File "bayesian_rnn.py", line 560, in <module>
    run()
  File "bayesian_rnn.py", line 510, in run
    m = PTBModel(is_training=True, config=config, input_=train_input)
  File "bayesian_rnn.py", line 229, in __init__
    bbb_bias=config.bbb_bias))
  File "bayesian_rnn.py", line 140, in __init__
    **self.name = name**
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1639, in __setattr__
    super(Layer, self).__setattr__(name, value)
AttributeError: can't set attribute

```
The problematic line  `self.name = name` comes from the BayesianLSTM class. This is the same error as the other issue however I am using Tensorflow 1.3.0 so the issue appears to be around using **Python 3.6** instead of Python3.5. Is there a way to amend to code so that it is compatible with Python 3.6.

**Comment by ghost** [comment]
I solved this issue by replacing 'name' with a substitute e.g. 'namex' everywhere in that class
